# This is a basic workflow to help you get started with Actions

name: make

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          git clone https://github.com/bitwiseshiftleft/sjcl.git
          ls -l
          ls -l sjcl
          cd sjcl
          ./configure --compress=yui --without-all --with-bitArray --with-codecString --with-codecHex --with-aes --with-cbc --with-sha256
          make
          ls -l
          cat sjcl.js
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sjcl.js
          path: |
            sjcl/sjcl.js
            retention-days: 90
